### ISSUE TITLE
Server-side pre-rendered images stuck at opacity: 0

### ISSUE THREAD

**Issue by austinpray** [Legitcode/image#4] opened 2015-09-18 20:41 UTC
When using the react-redux-universal-hot-example repo as a starting point (https://github.com/erikras/react-redux-universal-hot-example/tree/4705688b879f853ede08e3872bc083cc84227824)

My component:

```
<Image className="thumbnail" src="https://i.imgur.com/l50kGUz.png" />
```

The HTML that comes through in the view source:

```
<img class="thumbnail" src="https://images.unsplash.com/photo-1439003511744-2a0490ea0a88?q=80&amp;fm=jpg&amp;s=4dd5809698048edf8b82eedb82ca8cec" style="transition:opacity 1s;opacity:0;" data-reactid=".mzv5v08jcw.2.0.0.0">
```

Notice how the opacity is frozen at 0.

How to reproduce:
1. Clone that example repo down
2. `npm i --save legit-image`
3. Spam Image tags on the homepage or whatever page
4. `npm start`

Race condition with server-side rendering?

**Comment by zackify** [comment] 2015-09-18 20:44
Well it's stuck at opacity 0 because when it is initially rendered the opacity is supposed to be 0. I'm assuming you didn't mount the component on the client side after server rendering? I'm trying to think of a way to make this work correctly when you only want to server render...

**Comment by zackify** [comment] 2015-09-18 20:46
The only fix I can think of is that you have to include the component client side, and if server rendering pass a prop, something like `server={true}` so that it will just return a regular image tag if it's server rendered

**Comment by austinpray** [comment] 2015-09-18 20:50
I'll see if I can come back with a solution after looking at your code. Haven't peeped it yet.

**Comment by zackify** [comment] 2015-09-18 20:50
It's really simple, I completely see the problem, just unsure of the easiest way to fix it.

**Comment by constb** [comment] 2015-10-08 12:31
@zackify how about rendering it with `data-src`, loading image client side with `new Image` and then setting `src` and triggering transition? I think the root cause of this problem is that with server-rendered `img` tag image gets loaded before component is mounted and thus it doesn't receive `load` event.

**Comment by constb** [comment] 2015-10-08 12:32
@zackify also this way it would be easy to implement #3

**Comment by constb** [comment] 2015-10-08 12:34
@zackify actually, now that I thought about it, maybe you don't need `src` or `data-src` on initial render. After all you aren't exposing image url to any outside code. You can manually preload image and then set `src` only when it's already in the browser cache.

**Comment by zackify** [comment] 2015-10-08 19:54
@constb so what would be the real fix for this?

**Comment by austinpray** [comment] 2015-10-08 19:58
@zackify he's talking about a solution like this:

https://github.com/Flipboard/react-canvas/blob/0148605a654a8560a5bd8e9740579b719fec1b38/lib/ImageCache.js

https://github.com/Flipboard/react-canvas/blob/0148605a654a8560a5bd8e9740579b719fec1b38/lib/Image.js#L53

**Comment by constb** [comment] 2015-10-09 05:14
ah, I see the ambiguity here. by `new Image()` I meant `new window.Image()` of course. It has its own `onload` and `onerror`, and setting `src` on it triggers request without affecting the DOM. After it's loaded you just set DOM's `img.src` to the loaded Image's `src` and start the transition. Changing props.src should work the same way.

**Closed as completed** 2016-04-13 02:08 UTC

**Comment by zackify** [comment] 2016-04-13 02:10
@austinpray @constb sorry about it being 6 months later... I think I came up with an easy solution. If `window` is undefined, it will return opacity: 1. Even if you have React mount client side, you probably want images to show before it renders there.
